### ISSUE TITLE
host in SwaggerHttpService

### ISSUE THREAD

**Issue by mazorigal** [swagger-akka-http/swagger-akka-http#24]
Hi,

from http://swagger.io/specification/

"""
The host (name or ip) serving the API. This MUST be the host only and does not include the scheme nor sub-paths. It MAY include a port. If the host is not included, the host serving the documentation is to be used (including the port). The host does not support path templating.
"""

Is it possible to have same with swagger-akka-http ?

currently if I would not overwrite url from SwaggerHttpService, it will set its value to localhost by default. The issue that my service can run on different environments, and I cannot always know what would be the url domain name and port.

Thanks,

**Comment by pjfanning** [comment]
could you submit a pull request?

**Comment by pjfanning** [comment]
https://github.com/pjfanning/swagger-akka-http-sample has an example of setting the host/port for the swagger documentation.

**Comment by mazorigal** [comment]
Yes, it indeed have example. But what I would like is that in case the host would not be overwritten after extending SwaggerHttpService, it would not use "localhost" as default host value, but instead act according to the specification:

"""
If the host is not included, the host serving the documentation is to be used (including the port)
"""

**Comment by mazorigal** [comment]
ok, I ended up overwriting the swaggerConfig in  SwaggerHttpService.
Simply not providing any host for ```new Swagger()```.

```
override def swaggerConfig: Swagger = {
    val modifiedPath = prependSlashIfNecessary(basePath)
    val swagger = new Swagger().basePath(modifiedPath).info(info).scheme(scheme)
    swagger.setSecurityDefinitions(securitySchemeDefinitions.asJava)
    externalDocs match {
      case Some(ed) => swagger.externalDocs(ed)
      case _ => swagger
    }
  }
```

**Comment by pjfanning** [comment]
Since the existing `val host = "localhost"` approach makes it difficult to change the behaviour without causing upgrade issues for existing users, I'm not sure what is the best approach.
* we could assume that people typically override the `val host` so if we change that to default to "", then we could treat this value as meaning that we should not explicitly set the swagger host
* we could assume `host == ""` means not to explicitly set the swagger host but leave the default `val host = "localhost"` as it is
* we could add a boolean to control whether to set the swagger host
* if I was doing from scratch, I'd probably make the host an Option[String]

I favour the first solution as I intend to make the next release an 0.9.0 release in order to uptake the latest swagger version with the jackson 2.8 support - this is a prerequisite to me releasing a scala 2.12 cross compiled jar. So if I am bumping the release number, I can make some minor behaviour changes.

**Comment by mazorigal** [comment]
very well,
I am also prefer the Option usage, but understand the version constrains.
I think first solution would be fine for now, but for a major release you should indeed consider change it to Option[String].

**Comment by pjfanning** [comment]
Added to 0.8.2-SNAPSHOT jars on sonatype repo
