### ISSUE TITLE
SwaggerScalaModelConverter error related on `Jackson version`

### ISSUE THREAD

**Issue by kind0518** [swagger-akka-http/swagger-akka-http#63]
I am currently An error occurred.

> 

 java.util.ServiceConfigurationError: io.swagger.converter.ModelConverter: Provider io.swagger.scala.converter.SwaggerScalaModelConverter could not be instantiated

as you know, this error related on Jackson version.

My project uses jackson 2.9.2, is there a way to fix this error without lowering the version?

**Comment by pjfanning** [comment]
If all the jackson jars on your classpath are v2.9.2, then I expect things to work.
See https://github.com/pjfanning/swagger-akka-http-sample/tree/jackson-2.9.2 for a working example.
Jackson v2.9.0 had a breaking change that was fixed in v2.9.1.
When swagger-core 1.5.18 is released, with its upgrade of the jackson dependency, I will then update swagger-akka-http to match.

**Comment by pjfanning** [comment]
swagger-akka-http 0.12.0 changes jackson dependency to 2.9.2
