### ISSUE TITLE
How to handle nested urls

### ISSUE THREAD

**Issue by yadavan88** [swagger-akka-http/swagger-akka-http#9]
I have 3 services like shown below :
- /departments  (GET) 
    _get all departments_
- /departments  (POST)
    _create a new department_
- /departments/{id}/employees (GET) 
    _get all employees of a particular department_

I have one class _DepartmentRest_ which has all these 3 services and have annotated with swagger annotations. But when I check the swagger generated documentation, it only has 2 of the 3 services. I am not able to understand how to do for nested urls' with multiple params. I have scenarios where I have 9-10 separate url's under a single base url (eg: department )

I have added the code in a GIST [here][1]. 
[1]:https://gist.github.com/yadavan88/faab0ff69fe40fe4a646813451d6e63f

Can anyone please give a sample usage for my case ?

**Comment by pjfanning** [comment]
I think the issue is that you need to put a Path annotation on getEmpByDept.
As it stands, we cannot infer anything from the akka-http DSL (see this akka [issue](https://github.com/akka/akka/issues/16591)).
`@Path("{id}/employees")` will extend the path beyond what you have specified for the class (`@Path("departments")`).

**Comment by yadavan88** [comment]
@pjfanning Thank you very much for the response and it solved my issue. :)
